# Custom

add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$custom\
$cmd_duration\
$line_break\
$time\
$status\
$character\
"""

[status]
symbol = "✖ "
disabled = false
map_symbol = true
sigint_symbol = "INT "
signal_symbol = "$signal_name "
not_found_symbol = "✖ "

[directory]
truncation_symbol = "…/"
read_only = " "
truncation_length = 5
style = "bold purple"

[time]
disabled = false
format = "$time($style) "
style = "white"
time_format = "%I:%M %p"

[git_branch]
symbol = " "
style = "bold yellow"

[git_commit]
tag_disabled = false

[git_status]
ahead = "↑ ${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓ ${count}"
up_to_date = "[✔](green)"
conflicted = "= ${count}"
deleted = "✘ ${count}"
modified = "[+ ${count}](blue)"
stashed = "[⚑ ${count}](bold cyan)"
staged = "[●${count}](green)"
renamed = "[» ${count}](green)"
untracked = "[…${count}](purple)"

[aws]
style = "bold #ff9900"

[custom.midway]
description = "checks if midway credentials have expired"
when = "ls ~/mwinit-test.sh"
command = "~/mwinit-test.sh"
style = "bold red"